# Generated by Django 4.0.5 on 2022-06-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_name', models.CharField(max_length=100)),
                ('feedback_number', models.DecimalField(decimal_places=8, max_digits=10)),
                ('pub_date', models.DateTimeField(verbose_name='Request date')),
            ],
        ),
    ]
