# Generated by Django 4.0.5 on 2022-06-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_number',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
