# Generated by Django 4.0.5 on 2022-06-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_feedback_feedback_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='pub_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_number',
            new_name='number',
        ),
    ]
