# Generated by Django 4.0.5 on 2022-06-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_pub_date_feedback_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date',
        ),
    ]
